deploy-develop-heroku:
  stage: build
  only:
    - develop
  script:
    - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_DEVELOP.git HEAD:master -f

deploy-main-heroku:
  stage: build
  only:
    - main
  script:
    - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_PRODUCTION.git HEAD:master -f
